language: node_js
node_js:
    - "10"
    - "8"
jobs:
  include:
    - stage: test
      name: 'Linting'
      script: npm run lint
    - name: 'Coverage'
      script: npm run coveralls
    - stage: release
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
