name: Check
on: [push, pull_request]
jobs:
  release:
    needs: 
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit Test
        run: npm run build
        run: npm run coveralls